file:
  baseDirectory: "/Users/tobycc/Documents/Projects/GHCOTrading/src/main/resources/data"
  inputDirectory: "input"
  outputDirectory: "output"
  maxFilesToOutput: 2000

aggregation:
  outputToCsv: false
  outputToConsole: false